# Generated by Django 5.0.6 on 2024-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participante',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
