# Generated by Django 5.0.6 on 2024-06-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_participante_discord_participante_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
